export const regions = [
  { id: 1, value: "andijon", label: "Andijon" },
  { id: 2, value: "bukhara", label: "Buxoro" },
  { id: 3, value: "fergana", label: "Farg'ona" },
  { id: 4, value: "jizzakh", label: "Jizzax" },
  { id: 5, value: "namangan", label: "Namangan" },
  { id: 6, value: "navoiy", label: "Navoiy" },
  { id: 7, value: "qashqadaryo", label: "Qashqadaryo" },
  { id: 8, value: "qoraqalpogiston", label: "Qoraqalpog'iston" },
  { id: 9, value: "samarqand", label: "Samarqand" },
  { id: 10, value: "sirdaryo", label: "Sirdaryo" },
  { id: 11, value: "surxondaryo", label: "Surxondaryo" },
  { id: 12, value: "tashkent", label: "Toshkent" },
  { id: 13, value: "tashkent_vil", label: "Toshkent Viloyati" },
  { id: 14, value: "xorazm", label: "Xorazm" },
];
